scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 2s

    static_configs:
      - targets: [
        'localhost:9090',
      ]
        labels:
          service: 'app'
          group: 'testing'
          name: 'app-back'