scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 2s
    metrics_path: /api/metrics
    static_configs:
      - targets: [
        'host.docker.internal:8080',
      ]
        labels:
          service: 'app'
          group: 'testing'
          name: 'app-back'