export enum guessNumberValidationErrors {
  GAME_ID_IS_EMPTY = 'GAME_ID_IS_EMPTY',
  GAME_ID_IS_NOT_INT = 'GAME_ID_IS_NOT_INT',
  USER_ANSWER_IS_EMPTY = 'USER_ANSWER_IS_EMPTY',
  USER_ANSWER_IS_NOT_INT = 'USER_ANSWER_IS_NOT_INT',
  USER_ANSWER_MORE_THAN_MAX = 'USER_ANSWER_MORE_THAN_MAX',
  USER_ANSWER_LESS_THAN_MIN = 'USER_ANSWER_LESS_THAN_MIN',
}
